### ISSUE TITLE
Some questions about training a model on DSEC dataset.

### ISSUE THREAD

**Issue by bestrivenzc** [uzh-rpg/E-RAFT#3]
Hi，Mathias

Thanks for your cooperation!

The problem about the calibration between the event camera and the
frame camera has solved with your help! Thanks again!

The test code for the E-RAFT has published in github, it’s a
wonderful work!

In addition, I’d like to ask some questions about training the model
for estimating the optical flow on DSEC dataset. 

1) During supervision training on the model for E-RAFT, how to
preprocess the ground truth of optical flow. 

2) Currently, the network I proposed can converge on MVSEC dataset and
get reasonable results. But it cannot converge on the DSEC dataset
with the same network and the loss falls into local optimizaiton.  I
have tried many solutions (BN, Data Augmentation and so on), but still
don’t work. What’s the reason do you think cause this problem.

3) How to prepare the trianing data of DSEC for optical flow
estimation. My current approach is that choose the RGB frame and
events according to the timestamps of optical flow maps. For example,
the t1 and t2 is the timestamps of the optical flow map.  Then the
RGB_frame_1 and RGB_frame_2 which the t1 and t2 in  theis exposure
timestamps respectively. As for choose the events, just run the code
that “event_data  = eventslice.get_events(t1,t2)”.

I am not sure if the appoach mentioned above is correct. 

Looking forward to receiving your reply!

Best regards,

Chi

**Comment by magehrig** [comment]
Hi @bestrivenzc 

Thank you for your interest. Regarding your questions:

1. I cannot answer the question because it is very general. Maybe you can be more specific. Are you asking about loading of the optical flow maps from disk, or data augmentation?
2.  You also have to be more specific here. Is the dataloading identical to how it is done in this repository? Have you visualized the input to the network? If yes, does it look as expected?
3. yes this is correct. But you also need to load the events from t0 to t1. Because we use two event representations. So you need to have events between t0 and t1, and from t1 to t2.

**Comment by bestrivenzc** [comment]
hi, Mathias

Which specific video sequences shown in the Fig. 1 of E-RAFT. 

I wanna know which specific sequences and number of frames are under challenging illumination conditions.

Thanks.

**Comment by magehrig** [comment]
It should be Interlaken_00_d

**Comment by JamesYang110043** [comment]
Hi @magehrig 
I also have a question about the training process for the DSEC dataset. 
What sequence is used for validation?
