### ISSUE TITLE
The experiments results given in the paper

### ISSUE THREAD

**Issue by Hazeliii** [uzh-rpg/E-RAFT#4]
Hi，Mathias

There are 4 tables in the paper showing the experiment results. I assume they are all evaluation results.

The table 2 and table 3 are the MVSEC results. In my opinion,  the EV-FLOW and E-RAFT are trained and evaluated with MVSEC dataset. Am I right?

![table1](https://user-images.githubusercontent.com/53303848/147023129-9759b981-f1fb-4b96-9c91-e05f7a3a9137.png)

![table3](https://user-images.githubusercontent.com/53303848/147023237-9ef358b3-cb9e-45fd-80cb-60ac62b81772.png)

Are results in table 4 achieved by training EV-FLOW and E-RAFT both on DSEC dataset ? Or are they just trained on MVSEC but evaluated with DSEC？If they are trained and evaluated both on DSEC, **why are the results of E-RAFT not good as the results trained on MVSEC?**

![table4](https://user-images.githubusercontent.com/53303848/147023162-2ad3cf3c-e038-4e9c-a27d-81f3b661ff7b.png)

The ablation study are trained and evaluated separately on DSEC and MVSEC, right ?

![table5](https://user-images.githubusercontent.com/53303848/147023420-8148c892-c82c-40f1-b04f-e21388b8fe8b.png)

I hope that I express my problem clearly.

**Comment by Hazeliii** [comment]
I have another question about warm_start. Except for the _dataloder_ method , I didn't see any other differences in the released code. I thought there would be some operation about _forward_warp_ in the model function.

**Comment by magehrig** [comment]
The models are trained on either DSEC or MVSEC and tested on the corresponding test set. The same holds for the ablation study.

You cannot compare metrics achieved on the DSEC dataset with those on the MVSEC dataset because they are very different datasets. For example the optical flow magnitudes are much higher on DSEC than on MVSEC which naturally leads to higher errors in pixel space.

This is the code that does the forward warping: https://github.com/uzh-rpg/E-RAFT/blob/66af47f2eb45f13f117b0ed568961a6f1cdd0416/test.py#L199
